### ISSUE TITLE
In Docker mode, add options for Network mode, command and arguments

### ISSUE THREAD

**Issue by philwinder** [ContainerSolutions/mesos-starter#26]
E.g.
`mesos.docker.network="HOST"`
`mesos.docker.command="kibana"`
and
`mesos.docker.parameter="--port ${MESOS_PORT_0}"` (edited)

Port injection consider in another issue.

**Comment by mwl** [comment]
I think this can be achieved through SPEL, by evaluating the parameter string in the SPEL parser

**Comment by philwinder** [comment]
Duplicate of #25 #27 and #29
