### ISSUE TITLE
Provide port injection for arguments

### ISSUE THREAD

**Issue by philwinder** [ContainerSolutions/mesos-starter#27]
E.g.
`mesos.command.command=./webserver.sh`
`mesos.command.arguments=--port=$MESOS_PORT_0`
`mesos.docker.command=kibana`
`mesos.docker.arguments=--port=$MESOS_PORT_0`

Current thinking is to get the starter to create standardized env vars for the created ports and inject them into the container/command. Then the application can use the env vars.

Martin also suggested SPEL.

**Comment by mwl** [comment]
Assuming that we map all chosen ports to environment variables, then they should be available in the shell where you run the command?

**Comment by philwinder** [comment]
yes

**Comment by mwl** [comment]
This was fixed in #39.
